"""Criando tabelas de reservas e salas

Revision ID: 4f8431bd8b06
Revises:
Create Date: 2025-02-16 09:27:03.573810

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f8431bd8b06"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sala",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(50), nullable=False),
        sa.Column("capacidade", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reserva",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservado_por", sa.String(50), nullable=False),
        sa.Column("sala_reservada", sa.Integer(), nullable=False),
        sa.Column("data_inicial", sa.DateTime(), nullable=False),
        sa.Column("data_final", sa.DateTime(), nullable=False),
        sa.Column("descricao", sa.String(256), nullable=False),
        sa.Column("tipo_evento", sa.String(50), nullable=False),
        sa.Column("quantidade_pessoas", sa.Integer(), nullable=False),
        sa.Column("items", sa.String(25), nullable=True),
        sa.ForeignKeyConstraint(
            ["sala_reservada"],
            ["sala.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reserva")
    op.drop_table("sala")
    # ### end Alembic commands ###
