"""Criando as tabelas relacionadas os usuarios e aos tokens

Revision ID: 4fa82975ba25
Revises: 4f8431bd8b06
Create Date: 2025-02-17 13:37:42.008801

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fa82975ba25"
down_revision: Union[str, None] = "4f8431bd8b06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.String(450), nullable=False),
        sa.Column("refresh_token", sa.String(350), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("data_criacao", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("access_token"),
    )
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario", sa.String(50), nullable=False),
        sa.Column("email", sa.String(100), nullable=False),
        sa.Column("senha", sa.String(100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usuario")
    op.drop_table("token")
    # ### end Alembic commands ###
