"""
Removida a tabela de tokens.

Revision ID: 695025a5b152
Revises: ff6f1dbde8bd
Create Date: 2025-03-20 13:54:39.243161

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "695025a5b152"
down_revision: str | None = "ff6f1dbde8bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("id_usuario", sa.INTEGER(), nullable=False),
        sa.Column("access_token", sa.VARCHAR(length=450), nullable=False),
        sa.Column("refresh_token", sa.VARCHAR(length=350), nullable=False),
        sa.Column("status", sa.BOOLEAN(), nullable=False),
        sa.Column("data_criacao", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("access_token"),
    )
    # ### end Alembic commands ###
